### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/mm-docs#18]
https://oprypin.github.io/mkdocs-literate-nav/
https://github.com/oprypin/mkdocs-section-index

```
mkdocs-literate-nav
mkdocs-section-index
```

```yaml
    - literate-nav:
        nav_file: SUMMARY.md
    - section-index
```
